# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Commonuser_Book.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(855, 477)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(350, 70, 261, 81))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(90, 150, 151, 31))
        self.label_2.setObjectName("label_2")
        self.year = QtWidgets.QLineEdit(Dialog)
        self.year.setGeometry(QtCore.QRect(110, 200, 113, 21))
        self.year.setObjectName("year")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(240, 200, 31, 21))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(400, 200, 31, 21))
        self.label_4.setObjectName("label_4")
        self.month = QtWidgets.QLineEdit(Dialog)
        self.month.setGeometry(QtCore.QRect(270, 200, 113, 21))
        self.month.setObjectName("month")
        self.day = QtWidgets.QLineEdit(Dialog)
        self.day.setGeometry(QtCore.QRect(430, 200, 113, 21))
        self.day.setObjectName("day")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(560, 200, 31, 21))
        self.label_5.setObjectName("label_5")
        self.yes = QtWidgets.QPushButton(Dialog)
        self.yes.setGeometry(QtCore.QRect(160, 290, 101, 51))
        self.yes.setObjectName("yes")
        self.quit = QtWidgets.QPushButton(Dialog)
        self.quit.setGeometry(QtCore.QRect(540, 290, 101, 51))
        self.quit.setObjectName("quit")
        self.cancel = QtWidgets.QPushButton(Dialog)
        self.cancel.setGeometry(QtCore.QRect(350, 290, 121, 51))
        self.cancel.setObjectName("cancel")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:18pt; font-weight:600;\">接种预约</span></p></body></html>"))
        self.label_2.setText(_translate("Dialog", "请输入您的预约时间："))
        self.label_3.setText(_translate("Dialog", "年"))
        self.label_4.setText(_translate("Dialog", "月"))
        self.label_5.setText(_translate("Dialog", "日"))
        self.yes.setText(_translate("Dialog", "确认"))
        self.quit.setText(_translate("Dialog", "返回"))
        self.cancel.setText(_translate("Dialog", "取消预约"))
