# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Commonuserinfo.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class CommonuserInfo(object):
    def __init__(self, cid='none', cname='none', cage='none', csex='none', chomeid='none'):
        self.Id = cid
        self.Name = cname
        self.Age = cage
        self.Sex = csex
        self.Homeid = chomeid

    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setWindowModality(QtCore.Qt.ApplicationModal)
        Form.resize(869, 858)
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(290, 110, 251, 61))
        self.label_5.setObjectName("label_5")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(250, 230, 71, 41))
        self.label.setObjectName("label")
        self.ID = QtWidgets.QLabel(Form)
        self.ID.setGeometry(QtCore.QRect(350, 230, 301, 41))
        self.ID.setObjectName("ID")
        self.name = QtWidgets.QLabel(Form)
        self.name.setGeometry(QtCore.QRect(350, 280, 241, 41))
        self.name.setObjectName("name")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(250, 280, 71, 41))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(250, 330, 71, 41))
        self.label_3.setObjectName("label_3")
        self.age = QtWidgets.QLabel(Form)
        self.age.setGeometry(QtCore.QRect(350, 330, 241, 41))
        self.age.setObjectName("age")
        self.sex = QtWidgets.QLabel(Form)
        self.sex.setGeometry(QtCore.QRect(350, 380, 241, 41))
        self.sex.setObjectName("sex")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(250, 380, 71, 41))
        self.label_4.setObjectName("label_4")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(210, 430, 111, 41))
        self.label_6.setObjectName("label_6")
        self.family_code = QtWidgets.QLabel(Form)
        self.family_code.setGeometry(QtCore.QRect(350, 430, 241, 41))
        self.family_code.setObjectName("family_code")
        self.alter = QtWidgets.QPushButton(Form)
        self.alter.setGeometry(QtCore.QRect(240, 530, 111, 51))
        self.alter.setObjectName("alter")
        self.quit = QtWidgets.QPushButton(Form)
        self.quit.setGeometry(QtCore.QRect(470, 530, 111, 51))
        self.quit.setObjectName("quit")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_5.setText(_translate("Form",
                                        "<html><head/><body><p><span style=\" font-size:36pt; font-weight:600;\">个人信息</span></p></body></html>"))
        self.label.setText(
            _translate("Form", "<html><head/><body><p><span style=\" font-size:14pt;\">账号：</span></p></body></html>"))
        self.ID.setText(_translate("Form",
                                   "<html><head/><body><p><span style=\" font-size:14pt;\">" + self.Id + "</span></p></body></html>"))
        self.name.setText(_translate("Form",
                                     "<html><head/><body><p><span style=\" font-size:14pt;\">" + self.Name + "</span></p></body></html>"))
        self.label_2.setText(
            _translate("Form", "<html><head/><body><p><span style=\" font-size:14pt;\">姓名：</span></p></body></html>"))
        self.label_3.setText(
            _translate("Form", "<html><head/><body><p><span style=\" font-size:14pt;\">年龄：</span></p></body></html>"))
        self.age.setText(_translate("Form",
                                    "<html><head/><body><p><span style=\" font-size:14pt;\">" + self.Age + " 岁</span></p></body></html>"))
        self.sex.setText(_translate("Form",
                                    "<html><head/><body><p><span style=\" font-size:14pt;\">" + self.Sex + "</span></p></body></html>"))
        self.label_4.setText(
            _translate("Form", "<html><head/><body><p><span style=\" font-size:14pt;\">性别：</span></p></body></html>"))
        self.label_6.setText(
            _translate("Form", "<html><head/><body><p><span style=\" font-size:14pt;\">家庭编号：</span></p></body></html>"))
        self.family_code.setText(_translate("Form",
                                            "<html><head/><body><p><span style=\" font-size:14pt;\">" + self.Homeid + "</span></p></body></html>"))
        self.alter.setText(_translate("Form", "修改个人信息"))
        self.quit.setText(_translate("Form", "返回"))
