# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Commonuser_Info.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class CommonuserInfo(object):
    def __init__(self, cid='none', cname='none', cage='none', csex='none', chomeid='none', cphone='none', cIDCard='none'):
        self.Id = cid
        self.Name = cname
        self.Age = cage
        self.Sex = '男' if csex == 'M' else '女'
        self.Homeid = chomeid
        self.Phone = cphone
        self.IDCards = cIDCard

    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(984, 849)
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(370, 180, 251, 61))
        self.label_5.setObjectName("label_5")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(330, 350, 71, 41))
        self.label_2.setObjectName("label_2")
        self.age = QtWidgets.QLabel(Dialog)
        self.age.setGeometry(QtCore.QRect(430, 400, 241, 41))
        self.age.setObjectName("age")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(290, 500, 111, 41))
        self.label_6.setObjectName("label_6")
        self.name = QtWidgets.QLabel(Dialog)
        self.name.setGeometry(QtCore.QRect(430, 350, 241, 41))
        self.name.setObjectName("name")
        self.sex = QtWidgets.QLabel(Dialog)
        self.sex.setGeometry(QtCore.QRect(430, 450, 241, 41))
        self.sex.setObjectName("sex")
        self.family_code = QtWidgets.QLabel(Dialog)
        self.family_code.setGeometry(QtCore.QRect(430, 500, 241, 41))
        self.family_code.setObjectName("family_code")
        self.ID = QtWidgets.QLabel(Dialog)
        self.ID.setGeometry(QtCore.QRect(430, 300, 301, 41))
        self.ID.setObjectName("ID")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(330, 300, 71, 41))
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(330, 400, 71, 41))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(330, 450, 71, 41))
        self.label_4.setObjectName("label_4")
        self.alter = QtWidgets.QPushButton(Dialog)
        self.alter.setGeometry(QtCore.QRect(320, 710, 111, 51))
        self.alter.setObjectName("alter")
        self.IDCard = QtWidgets.QLabel(Dialog)
        self.IDCard.setGeometry(QtCore.QRect(430, 600, 241, 41))
        self.IDCard.setObjectName("IDCard")
        self.quit = QtWidgets.QPushButton(Dialog)
        self.quit.setGeometry(QtCore.QRect(550, 710, 111, 51))
        self.quit.setObjectName("quit")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(290, 550, 111, 41))
        self.label_7.setObjectName("label_7")
        self.phone = QtWidgets.QLabel(Dialog)
        self.phone.setGeometry(QtCore.QRect(430, 550, 241, 41))
        self.phone.setObjectName("phone")
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(290, 600, 111, 41))
        self.label_8.setObjectName("label_8")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_5.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:36pt; font-weight:600;\">个人信息</span></p></body></html>"))
        self.label_2.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:14pt;\">姓名：</span></p></body></html>"))
        self.age.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:14pt;\">" + str(self.Age) + "</span></p></body></html>"))
        self.label_6.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:14pt;\">家庭编号：</span></p></body></html>"))
        self.name.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:14pt;\">" + str(self.Name) + "</span></p></body></html>"))
        self.sex.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:14pt;\">" + str(self.Sex) + "</span></p></body></html>"))
        self.family_code.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:14pt;\">" + str(self.Homeid) + "</span></p></body></html>"))
        self.ID.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:14pt;\">" + str(self.Id) + "</span></p></body></html>"))
        self.label.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:14pt;\">账号：</span></p></body></html>"))
        self.label_3.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:14pt;\">年龄：</span></p></body></html>"))
        self.label_4.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:14pt;\">性别：</span></p></body></html>"))
        self.alter.setText(_translate("Dialog", "修改个人信息"))
        self.IDCard.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:14pt;\">" + str(self.IDCards) + "</span></p></body></html>"))
        self.quit.setText(_translate("Dialog", "返回"))
        self.label_7.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:14pt;\">手机号：</span></p></body></html>"))
        self.phone.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:14pt;\">" + str(self.Phone) + "</span></p></body></html>"))
        self.label_8.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:14pt;\">身份证号：</span></p></body></html>"))

class Commonuser_Alter(object):
    def __init__(self, cid='none', cIDCard='none'):
        self.Ids = cid
        self.IDCards = cIDCard

    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(913, 826)
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(930, 750, 251, 61))
        self.label_5.setObjectName("label_5")
        self.ID = QtWidgets.QLabel(Dialog)
        self.ID.setGeometry(QtCore.QRect(990, 870, 301, 41))
        self.ID.setObjectName("ID")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(890, 970, 71, 41))
        self.label_3.setObjectName("label_3")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(850, 1070, 111, 41))
        self.label_6.setObjectName("label_6")
        self.sex = QtWidgets.QLabel(Dialog)
        self.sex.setGeometry(QtCore.QRect(990, 1020, 241, 41))
        self.sex.setObjectName("sex")
        self.alter = QtWidgets.QPushButton(Dialog)
        self.alter.setGeometry(QtCore.QRect(880, 1170, 111, 51))
        self.alter.setObjectName("alter")
        self.quit = QtWidgets.QPushButton(Dialog)
        self.quit.setGeometry(QtCore.QRect(1110, 1170, 111, 51))
        self.quit.setObjectName("quit")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(890, 870, 71, 41))
        self.label.setObjectName("label")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(890, 1020, 71, 41))
        self.label_4.setObjectName("label_4")
        self.age = QtWidgets.QLabel(Dialog)
        self.age.setGeometry(QtCore.QRect(990, 970, 241, 41))
        self.age.setObjectName("age")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(890, 920, 71, 41))
        self.label_2.setObjectName("label_2")
        self.name = QtWidgets.QLabel(Dialog)
        self.name.setGeometry(QtCore.QRect(990, 920, 241, 41))
        self.name.setObjectName("name")
        self.family_code = QtWidgets.QLabel(Dialog)
        self.family_code.setGeometry(QtCore.QRect(990, 1070, 241, 41))
        self.family_code.setObjectName("family_code")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(280, 170, 371, 61))
        self.label_7.setObjectName("label_7")
        self.Id = QtWidgets.QLabel(Dialog)
        self.Id.setGeometry(QtCore.QRect(430, 280, 301, 41))
        self.Id.setObjectName("Id")
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(330, 380, 71, 41))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setGeometry(QtCore.QRect(290, 480, 111, 41))
        self.label_9.setObjectName("label_9")
        self.Yes = QtWidgets.QPushButton(Dialog)
        self.Yes.setGeometry(QtCore.QRect(320, 690, 111, 51))
        self.Yes.setObjectName("Yes")
        self.Quit = QtWidgets.QPushButton(Dialog)
        self.Quit.setGeometry(QtCore.QRect(550, 690, 111, 51))
        self.Quit.setObjectName("Quit")
        self.label_10 = QtWidgets.QLabel(Dialog)
        self.label_10.setGeometry(QtCore.QRect(330, 280, 71, 41))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(Dialog)
        self.label_11.setGeometry(QtCore.QRect(330, 430, 71, 41))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(Dialog)
        self.label_12.setGeometry(QtCore.QRect(330, 330, 71, 41))
        self.label_12.setObjectName("label_12")
        self.Name = QtWidgets.QLineEdit(Dialog)
        self.Name.setGeometry(QtCore.QRect(440, 330, 191, 31))
        self.Name.setObjectName("Name")
        self.Age = QtWidgets.QLineEdit(Dialog)
        self.Age.setGeometry(QtCore.QRect(440, 390, 191, 31))
        self.Age.setObjectName("Age")
        self.Sex = QtWidgets.QLineEdit(Dialog)
        self.Sex.setGeometry(QtCore.QRect(440, 440, 191, 31))
        self.Sex.setObjectName("Sex")
        self.Homeid = QtWidgets.QLineEdit(Dialog)
        self.Homeid.setGeometry(QtCore.QRect(440, 490, 191, 31))
        self.Homeid.setObjectName("Homeid")
        self.ID_3 = QtWidgets.QLabel(Dialog)
        self.ID_3.setGeometry(QtCore.QRect(640, 490, 301, 41))
        self.ID_3.setObjectName("ID_3")
        self.Phone = QtWidgets.QLineEdit(Dialog)
        self.Phone.setGeometry(QtCore.QRect(440, 540, 191, 31))
        self.Phone.setObjectName("Phone")
        self.label_13 = QtWidgets.QLabel(Dialog)
        self.label_13.setGeometry(QtCore.QRect(290, 530, 111, 41))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(Dialog)
        self.label_14.setGeometry(QtCore.QRect(290, 590, 111, 41))
        self.label_14.setObjectName("label_14")
        self.IDCard = QtWidgets.QLabel(Dialog)
        self.IDCard.setGeometry(QtCore.QRect(430, 590, 301, 41))
        self.IDCard.setObjectName("IDCard")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_5.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:36pt; font-weight:600;\">个人信息</span></p></body></html>"))
        self.ID.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:14pt;\">(ID)</span></p></body></html>"))
        self.label_3.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:14pt;\">年龄：</span></p></body></html>"))
        self.label_6.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:14pt;\">家庭编号：</span></p></body></html>"))
        self.sex.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:14pt;\">（您的性别）</span></p></body></html>"))
        self.alter.setText(_translate("Dialog", "修改个人信息"))
        self.quit.setText(_translate("Dialog", "返回"))
        self.label.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:14pt;\">账号：</span></p></body></html>"))
        self.label_4.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:14pt;\">性别：</span></p></body></html>"))
        self.age.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:14pt;\">（您的年龄）</span></p></body></html>"))
        self.label_2.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:14pt;\">姓名：</span></p></body></html>"))
        self.name.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:14pt;\">（您的姓名）</span></p></body></html>"))
        self.family_code.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:14pt;\">（您的家庭编号）</span></p></body></html>"))
        self.label_7.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:36pt; font-weight:600;\">修改个人信息</span></p></body></html>"))
        self.Id.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:14pt;\">" + str(self.Ids) + "</span></p></body></html>"))
        self.label_8.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:14pt;\">年龄：</span></p></body></html>"))
        self.label_9.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:14pt;\">家庭编号：</span></p></body></html>"))
        self.Yes.setText(_translate("Dialog", "确认"))
        self.Quit.setText(_translate("Dialog", "返回"))
        self.label_10.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:14pt;\">账号：</span></p></body></html>"))
        self.label_11.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:14pt;\">性别：</span></p></body></html>"))
        self.label_12.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:14pt;\">姓名：</span></p></body></html>"))
        self.ID_3.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:14pt;\">（输入8位家庭编号）</span></p></body></html>"))
        self.label_13.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:14pt;\">手机号：</span></p></body></html>"))
        self.label_14.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:14pt;\">身份证：</span></p></body></html>"))
        self.IDCard.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:14pt;\">" + str(self.IDCards) + "</span></p></body></html>"))

class CommonuserBook(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(855, 477)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(350, 70, 261, 81))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(90, 150, 151, 31))
        self.label_2.setObjectName("label_2")
        self.year = QtWidgets.QLineEdit(Dialog)
        self.year.setGeometry(QtCore.QRect(110, 200, 113, 21))
        self.year.setObjectName("year")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(240, 200, 31, 21))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(400, 200, 31, 21))
        self.label_4.setObjectName("label_4")
        self.month = QtWidgets.QLineEdit(Dialog)
        self.month.setGeometry(QtCore.QRect(270, 200, 113, 21))
        self.month.setObjectName("month")
        self.day = QtWidgets.QLineEdit(Dialog)
        self.day.setGeometry(QtCore.QRect(430, 200, 113, 21))
        self.day.setObjectName("day")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(560, 200, 31, 21))
        self.label_5.setObjectName("label_5")
        self.yes = QtWidgets.QPushButton(Dialog)
        self.yes.setGeometry(QtCore.QRect(160, 290, 101, 51))
        self.yes.setObjectName("yes")
        self.quit = QtWidgets.QPushButton(Dialog)
        self.quit.setGeometry(QtCore.QRect(540, 290, 101, 51))
        self.quit.setObjectName("quit")
        self.cancel = QtWidgets.QPushButton(Dialog)
        self.cancel.setGeometry(QtCore.QRect(350, 290, 121, 51))
        self.cancel.setObjectName("cancel")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:18pt; font-weight:600;\">接种预约</span></p></body></html>"))
        self.label_2.setText(_translate("Dialog", "请输入您的预约时间："))
        self.label_3.setText(_translate("Dialog", "年"))
        self.label_4.setText(_translate("Dialog", "月"))
        self.label_5.setText(_translate("Dialog", "日"))
        self.yes.setText(_translate("Dialog", "确认"))
        self.quit.setText(_translate("Dialog", "返回"))
        self.cancel.setText(_translate("Dialog", "取消预约"))


class BookInfo(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(412, 115)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(110, 40, 301, 31))
        self.label.setObjectName("label")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:20pt;\">预约成功！</span></p></body></html>"))

class BookCancelInfo(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(412, 115)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(110, 40, 301, 31))
        self.label.setObjectName("label")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:20pt;\">取消成功！</span></p></body></html>"))

class CommonuserBadReaction(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(850, 475)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(300, 50, 271, 51))
        self.label.setObjectName("label")
        self.bad_reaction = QtWidgets.QTextEdit(Dialog)
        self.bad_reaction.setGeometry(QtCore.QRect(90, 150, 661, 191))
        self.bad_reaction.setObjectName("bad_reaction")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(90, 110, 251, 16))
        self.label_2.setObjectName("label_2")
        self.yes = QtWidgets.QPushButton(Dialog)
        self.yes.setGeometry(QtCore.QRect(200, 380, 131, 51))
        self.yes.setObjectName("yes")
        self.quit = QtWidgets.QPushButton(Dialog)
        self.quit.setGeometry(QtCore.QRect(470, 380, 131, 51))
        self.quit.setObjectName("quit")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:26pt; font-weight:600;\">不良反应反馈</span></p></body></html>"))
        self.label_2.setText(_translate("Dialog", "请输入您的不良反应：(50字以内)"))
        self.yes.setText(_translate("Dialog", "确定"))
        self.quit.setText(_translate("Dialog", "返回"))

class ReactionInfo(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(412, 115)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(110, 40, 301, 31))
        self.label.setObjectName("label")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:20pt;\">反馈成功！</span></p></body></html>"))

