# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Commonuser_BadReaction.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class CommonuserBadReaction(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(850, 475)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(300, 50, 271, 51))
        self.label.setObjectName("label")
        self.bad_reaction = QtWidgets.QTextEdit(Dialog)
        self.bad_reaction.setGeometry(QtCore.QRect(90, 150, 661, 191))
        self.bad_reaction.setObjectName("bad_reaction")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(90, 110, 251, 16))
        self.label_2.setObjectName("label_2")
        self.yes = QtWidgets.QPushButton(Dialog)
        self.yes.setGeometry(QtCore.QRect(200, 380, 131, 51))
        self.yes.setObjectName("yes")
        self.quit = QtWidgets.QPushButton(Dialog)
        self.quit.setGeometry(QtCore.QRect(470, 380, 131, 51))
        self.quit.setObjectName("quit")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:26pt; font-weight:600;\">不良反应反馈</span></p></body></html>"))
        self.label_2.setText(_translate("Dialog", "请输入您的不良反应：(50字以内)"))
        self.yes.setText(_translate("Dialog", "确定"))
        self.quit.setText(_translate("Dialog", "返回"))
