# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'HomeInfo.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class HomeInfoManage(object):
    def __init__(self, family_info=None):
        self.family_info = family_info
        nums = 0 if self.family_info==None else len(self.family_info)
        #print(nums, type(nums))
        if nums == 0:
            self.number1_info = self.number2_info = self.number3_info = self.number4_info = '(未添加家庭成员信息)'
        elif nums == 1:
            self.number2_info = self.number3_info = self.number4_info = '(未添加家庭成员信息)'
            self.number1_info = "姓名：'%s', 年龄：'%s'岁, 性别：'%s', 手机号：'%s', 身份证号：'%s'" % (self.family_info[0][0],self.family_info[0][1],self.family_info[0][2],self.family_info[0][3],self.family_info[0][4])
        elif nums == 2:
            self.number3_info = self.number4_info = '(未添加家庭成员信息)'
            self.number1_info = "姓名：'%s', 年龄：'%s'岁, 性别：'%s', 手机号：'%s', 身份证号：'%s'" % (self.family_info[0][0], self.family_info[0][1], self.family_info[0][2], self.family_info[0][3],self.family_info[0][4])
            self.number2_info = "姓名：'%s', 年龄：'%s'岁, 性别：'%s', 手机号：'%s', 身份证号：'%s'" % (self.family_info[1][0], self.family_info[1][1], self.family_info[1][2], self.family_info[1][3],self.family_info[1][4])
        elif nums == 3:
            self.number4_info = '(未添加家庭成员信息)'
            self.number1_info = "姓名：'%s', 年龄：'%s'岁, 性别：'%s', 手机号：'%s', 身份证号：'%s'" % (self.family_info[0][0], self.family_info[0][1], self.family_info[0][2], self.family_info[0][3],self.family_info[0][4])
            self.number2_info = "姓名：'%s', 年龄：'%s'岁, 性别：'%s', 手机号：'%s', 身份证号：'%s'" % (self.family_info[1][0], self.family_info[1][1], self.family_info[1][2], self.family_info[1][3],self.family_info[1][4])
            self.number3_info = "姓名：'%s', 年龄：'%s'岁, 性别：'%s', 手机号：'%s', 身份证号：'%s'" % (self.family_info[2][0], self.family_info[2][1], self.family_info[2][2], self.family_info[2][3],self.family_info[2][4])
        else:
            self.number1_info = "姓名：'%s', 年龄：'%s'岁, 性别：'%s', 手机号：'%s', 身份证号：'%s'" % (self.family_info[0][0], self.family_info[0][1], self.family_info[0][2], self.family_info[0][3],self.family_info[0][4])
            self.number2_info = "姓名：'%s', 年龄：'%s'岁, 性别：'%s', 手机号：'%s', 身份证号：'%s'" % (self.family_info[1][0], self.family_info[1][1], self.family_info[1][2], self.family_info[1][3],self.family_info[1][4])
            self.number3_info = "姓名：'%s', 年龄：'%s'岁, 性别：'%s', 手机号：'%s', 身份证号：'%s'" % (self.family_info[2][0], self.family_info[2][1], self.family_info[2][2], self.family_info[2][3],self.family_info[2][4])
            self.number4_info = "姓名：'%s', 年龄：'%s'岁, 性别：'%s', 手机号：'%s', 身份证号：'%s'" % (self.family_info[3][0], self.family_info[3][1], self.family_info[3][2], self.family_info[3][3],self.family_info[3][4])
        return

    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1023, 811)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(380, 70, 321, 81))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(70, 200, 131, 31))
        self.label_2.setObjectName("label_2")
        self.person1 = QtWidgets.QLabel(Dialog)
        self.person1.setGeometry(QtCore.QRect(220, 200, 781, 31))
        self.person1.setObjectName("person1")
        self.person2 = QtWidgets.QLabel(Dialog)
        self.person2.setGeometry(QtCore.QRect(220, 250, 781, 31))
        self.person2.setObjectName("person2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(70, 250, 131, 31))
        self.label_3.setObjectName("label_3")
        self.person3 = QtWidgets.QLabel(Dialog)
        self.person3.setGeometry(QtCore.QRect(220, 300, 781, 31))
        self.person3.setObjectName("person3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(70, 300, 131, 31))
        self.label_4.setObjectName("label_4")
        self.person4 = QtWidgets.QLabel(Dialog)
        self.person4.setGeometry(QtCore.QRect(220, 350, 781, 31))
        self.person4.setObjectName("person4")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(70, 350, 131, 31))
        self.label_5.setObjectName("label_5")
        self.del1 = QtWidgets.QPushButton(Dialog)
        self.del1.setGeometry(QtCore.QRect(960, 190, 51, 31))
        self.del1.setObjectName("del1")
        self.del2 = QtWidgets.QPushButton(Dialog)
        self.del2.setGeometry(QtCore.QRect(960, 240, 51, 31))
        self.del2.setObjectName("del2")
        self.del3 = QtWidgets.QPushButton(Dialog)
        self.del3.setGeometry(QtCore.QRect(960, 290, 51, 31))
        self.del3.setObjectName("del3")
        self.del4 = QtWidgets.QPushButton(Dialog)
        self.del4.setGeometry(QtCore.QRect(960, 340, 51, 31))
        self.del4.setObjectName("del4")
        self.add4 = QtWidgets.QPushButton(Dialog)
        self.add4.setGeometry(QtCore.QRect(900, 340, 51, 31))
        self.add4.setObjectName("add4")
        self.add2 = QtWidgets.QPushButton(Dialog)
        self.add2.setGeometry(QtCore.QRect(900, 240, 51, 31))
        self.add2.setObjectName("add2")
        self.add3 = QtWidgets.QPushButton(Dialog)
        self.add3.setGeometry(QtCore.QRect(900, 290, 51, 31))
        self.add3.setObjectName("add3")
        self.add1 = QtWidgets.QPushButton(Dialog)
        self.add1.setGeometry(QtCore.QRect(900, 190, 51, 31))
        self.add1.setObjectName("add1")
        self.quit = QtWidgets.QPushButton(Dialog)
        self.quit.setGeometry(QtCore.QRect(600, 500, 93, 51))
        self.quit.setObjectName("quit")
        self.alter = QtWidgets.QPushButton(Dialog)
        self.alter.setGeometry(QtCore.QRect(420, 500, 93, 51))
        self.alter.setObjectName("alter")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:28pt; font-weight:600;\">家庭信息管理</span></p></body></html>"))
        self.label_2.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">家庭成员1：</span></p></body></html>"))
        self.person1.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:8pt; font-weight:200;\">" + self.number1_info + "</span></p></body></html>"))
        self.person2.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:8pt; font-weight:200;\">" + self.number2_info + "</span></p></body></html>"))
        self.label_3.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">家庭成员2：</span></p></body></html>"))
        self.person3.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:8pt; font-weight:200;\">" + self.number3_info + "</span></p></body></html>"))
        self.label_4.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">家庭成员3：</span></p></body></html>"))
        self.person4.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:8pt; font-weight:200;\">" + self.number4_info + "</span></p></body></html>"))
        self.label_5.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">家庭成员4：</span></p></body></html>"))
        self.del1.setText(_translate("Dialog", "删除"))
        self.del2.setText(_translate("Dialog", "删除"))
        self.del3.setText(_translate("Dialog", "删除"))
        self.del4.setText(_translate("Dialog", "删除"))
        self.add4.setText(_translate("Dialog", "添加"))
        self.add2.setText(_translate("Dialog", "添加"))
        self.add3.setText(_translate("Dialog", "添加"))
        self.add1.setText(_translate("Dialog", "添加"))
        self.quit.setText(_translate("Dialog", "返回"))
        self.alter.setText(_translate("Dialog", "确认"))

class DelInfo(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(412, 115)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(110, 40, 301, 31))
        self.label.setObjectName("label")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:20pt;\">删除成功！</span></p></body></html>"))
