# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'HospitalInoculate.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Inoculate(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(628, 584)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(260, 30, 201, 41))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(130, 110, 91, 21))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(130, 150, 91, 21))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(130, 190, 91, 21))
        self.label_4.setObjectName("label_4")
        self.IdCard = QtWidgets.QLineEdit(Dialog)
        self.IdCard.setGeometry(QtCore.QRect(240, 100, 221, 31))
        self.IdCard.setObjectName("IdCard")
        self.VaccineType = QtWidgets.QLineEdit(Dialog)
        self.VaccineType.setGeometry(QtCore.QRect(240, 150, 221, 31))
        self.VaccineType.setObjectName("VaccineType")
        self.Time1 = QtWidgets.QLineEdit(Dialog)
        self.Time1.setGeometry(QtCore.QRect(240, 190, 51, 31))
        self.Time1.setObjectName("Time1")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(300, 200, 16, 16))
        self.label_5.setObjectName("label_5")
        self.Time2 = QtWidgets.QLineEdit(Dialog)
        self.Time2.setGeometry(QtCore.QRect(330, 190, 51, 31))
        self.Time2.setObjectName("Time2")
        self.Time3 = QtWidgets.QLineEdit(Dialog)
        self.Time3.setGeometry(QtCore.QRect(410, 190, 51, 31))
        self.Time3.setObjectName("Time3")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(390, 200, 16, 16))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(470, 200, 16, 16))
        self.label_7.setObjectName("label_7")
        self.Yes = QtWidgets.QPushButton(Dialog)
        self.Yes.setGeometry(QtCore.QRect(210, 250, 91, 51))
        self.Yes.setObjectName("Yes")
        self.Quit = QtWidgets.QPushButton(Dialog)
        self.Quit.setGeometry(QtCore.QRect(370, 250, 91, 51))
        self.Quit.setObjectName("Quit")
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(250, 340, 201, 41))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setGeometry(QtCore.QRect(100, 400, 311, 21))
        self.label_9.setObjectName("label_9")
        self.IdCard_2 = QtWidgets.QLineEdit(Dialog)
        self.IdCard_2.setGeometry(QtCore.QRect(240, 440, 221, 31))
        self.IdCard_2.setObjectName("IdCard_2")
        self.label_10 = QtWidgets.QLabel(Dialog)
        self.label_10.setGeometry(QtCore.QRect(130, 450, 91, 21))
        self.label_10.setObjectName("label_10")
        self.Search = QtWidgets.QPushButton(Dialog)
        self.Search.setGeometry(QtCore.QRect(300, 500, 91, 51))
        self.Search.setObjectName("Search")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:18pt; font-weight:600;\">添加接种信息</span></p></body></html>"))
        self.label_2.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:12pt;\">身份证号：</span></p></body></html>"))
        self.label_3.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:12pt;\">疫苗类型：</span></p></body></html>"))
        self.label_4.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:12pt;\">接种时间：</span></p></body></html>"))
        self.label_5.setText(_translate("Dialog", "年"))
        self.label_6.setText(_translate("Dialog", "月"))
        self.label_7.setText(_translate("Dialog", "日"))
        self.Yes.setText(_translate("Dialog", "确认添加"))
        self.Quit.setText(_translate("Dialog", "返回"))
        self.label_8.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:18pt; font-weight:600;\">查看接种信息</span></p></body></html>"))
        self.label_9.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:12pt;\">请输入您要查找用户的身份证号：</span></p></body></html>"))
        self.label_10.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:12pt;\">身份证号：</span></p></body></html>"))
        self.Search.setText(_translate("Dialog", "查看"))
