# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LoginError1.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class LoginError_Dialog1(object):
    def setupUi(self, LoginError1):
        LoginError1.setObjectName("LoginError1")
        LoginError1.resize(324, 129)
        self.label = QtWidgets.QLabel(LoginError1)
        self.label.setGeometry(QtCore.QRect(50, 40, 271, 51))
        self.label.setObjectName("label")

        self.retranslateUi(LoginError1)
        QtCore.QMetaObject.connectSlotsByName(LoginError1)

    def retranslateUi(self, LoginError1):
        _translate = QtCore.QCoreApplication.translate
        LoginError1.setWindowTitle(_translate("LoginError1", "Dialog"))
        self.label.setText(_translate("LoginError1", "<html><head/><body><p><span style=\" font-size:16pt;\">输入不可以为空！</span></p></body></html>"))

class LoginError_Dialog2(object):
    def setupUi(self, LoginError1):
        LoginError1.setObjectName("LoginError1")
        LoginError1.resize(324, 129)
        self.label = QtWidgets.QLabel(LoginError1)
        self.label.setGeometry(QtCore.QRect(50, 40, 271, 51))
        self.label.setObjectName("label")

        self.retranslateUi(LoginError1)
        QtCore.QMetaObject.connectSlotsByName(LoginError1)

    def retranslateUi(self, LoginError1):
        _translate = QtCore.QCoreApplication.translate
        LoginError1.setWindowTitle(_translate("LoginError1", "Dialog"))
        self.label.setText(_translate("LoginError1", "<html><head/><body><p><span style=\" font-size:16pt;\">您还未注册，请注册！</span></p></body></html>"))

class LoginError_Dialog3(object):
    def setupUi(self, LoginError1):
        LoginError1.setObjectName("LoginError1")
        LoginError1.resize(324, 129)
        self.label = QtWidgets.QLabel(LoginError1)
        self.label.setGeometry(QtCore.QRect(50, 40, 271, 51))
        self.label.setObjectName("label")

        self.retranslateUi(LoginError1)
        QtCore.QMetaObject.connectSlotsByName(LoginError1)

    def retranslateUi(self, LoginError1):
        _translate = QtCore.QCoreApplication.translate
        LoginError1.setWindowTitle(_translate("LoginError1", "Dialog"))
        self.label.setText(_translate("LoginError1", "<html><head/><body><p><span style=\" font-size:16pt;\">您的密码有误！</span></p></body></html>"))
